#!/usr/bin/env python3
"""Turn matrix [[blank:item-*]] markers into durable, interactive inputs."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


DEFAULT_PAGES = (
    "pg086_sec001.html",
    "pg098_sec001.html",
    "pg108_sec002.html",
    "pg109_sec002.html",
    "pg115_sec001.html",
    "pg116_sec002.html",
    "pg116_sec003.html",
    "pg132_sec001.html",
    "pg134_sec003.html",
    "pg135_sec001.html",
    "pg135_sec004.html",
)

MARKER_RE = re.compile(r"\[\[blank:(item-\d+)(?::[^\]]+)?\]\]", re.IGNORECASE)
ELEMENT_RE = re.compile(
    r'<(?P<tag>span|p|div)(?P<attrs>[^>]*\bdata-id="(?P<id>[^"]+)"[^>]*)>'
    r'(?P<content>[^<]*\[\[blank:item-[^<]+?)</(?P=tag)>',
    re.IGNORECASE,
)
ANSWERS_RE = re.compile(r"window\.correctAnswers\s*=\s*JSON\.parse\('([^']*)'\)")
DATA_ID_RE = re.compile(r'\s+data-id="[^"]+"')
OVERRIDES_RE = re.compile(r"Object\.assign\(.*?,\s*(\{.*\})\s*,\s*\);", re.DOTALL)

INPUT_CLASS = (
    "inline-block min-w-24 max-w-full border-0 border-b-2 border-slate-600 "
    "bg-transparent px-2 text-center align-baseline outline-none focus:border-sky-600"
)


def split_content(content: str) -> tuple[list[str], list[re.Match[str]]]:
    markers = list(MARKER_RE.finditer(content))
    segments: list[str] = []
    cursor = 0
    for marker in markers:
        segments.append(content[cursor : marker.start()])
        cursor = marker.end()
    segments.append(content[cursor:])
    return segments, markers


def reading_segment(content: str) -> str:
    segments, _ = split_content(content)
    return next((segment.strip() for segment in segments if segment.strip()), "")


def input_width(answer: str) -> float:
    if not answer:
        return 12.0
    return max(6.0, min(20.0, len(answer) * 0.72 + 2.5))


def render_element(match: re.Match[str], answers: dict[str, str], counter: list[int]) -> str:
    tag = match.group("tag")
    data_id = match.group("id")
    content = match.group("content")
    attrs = DATA_ID_RE.sub("", match.group("attrs"), count=1)
    segments, markers = split_content(content)
    owner_index = next((i for i, segment in enumerate(segments) if segment.strip()), 0)

    rendered: list[str] = []
    for index, segment in enumerate(segments):
        if segment:
            if index == owner_index:
                rendered.append(f'<span data-id="{data_id}">{segment}</span>')
            else:
                rendered.append(f"<span>{segment}</span>")
        if index >= len(markers):
            continue

        item = markers[index].group(1).lower()
        answer = answers.get(item, "")
        aria_index = counter[0]
        counter[0] += 1
        rendered.append(
            f'<input type="text" data-aria-id="aria-matrix-{aria_index}" '
            f'data-activity-item="{item}" aria-label="Jibu la {item.replace("-", " ")}" '
            f'tabindex="0" class="{INPUT_CLASS}" style="width:{input_width(answer):.1f}rem" />'
        )

    return f"<{tag}{attrs}>{''.join(rendered)}</{tag}>"


def load_answers(html: str) -> dict[str, str]:
    match = ANSWERS_RE.search(html)
    return json.loads(match.group(1)) if match else {}


def transform_page(path: Path) -> tuple[int, dict[str, str]]:
    html = path.read_text(encoding="utf-8")
    answers = load_answers(html)
    overrides: dict[str, str] = {}
    counter = [0]

    for match in ELEMENT_RE.finditer(html):
        overrides[match.group("id")] = reading_segment(match.group("content"))

    transformed, element_count = ELEMENT_RE.subn(
        lambda match: render_element(match, answers, counter), html
    )
    if element_count:
        path.write_text(transformed, encoding="utf-8", newline="")
    return counter[0], overrides


def write_overrides(path: Path, overrides: dict[str, str]) -> None:
    payload = json.dumps(overrides, ensure_ascii=True, indent=2, sort_keys=True)
    content = (
        "// Generated by tools/materialize_matrix_blank_inputs.py.\n"
        "window.__ADT_READING_TEXT_OVERRIDES__ = Object.assign(\n"
        "  window.__ADT_READING_TEXT_OVERRIDES__ || {},\n"
        f"  {payload},\n"
        ");\n"
    )
    path.write_text(content, encoding="utf-8", newline="")


def load_existing_overrides(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    match = OVERRIDES_RE.search(path.read_text(encoding="utf-8"))
    return json.loads(match.group(1)) if match else {}


def add_easy_read_overrides(root: Path, overrides: dict[str, str]) -> None:
    texts_path = root / "content" / "i18n" / "sw-TZ" / "texts.json"
    texts = json.loads(texts_path.read_text(encoding="utf-8"))
    normal_ids = [key for key in overrides if not key.endswith("_easy_read")]
    for data_id in normal_ids:
        easy_text = texts.get(f"{data_id}_easy_read", "")
        overrides[f"{data_id}_easy_read"] = (
            reading_segment(easy_text) if MARKER_RE.search(easy_text) else overrides[data_id]
        )


def add_override_script(root: Path) -> int:
    old = '    <script src="./assets/reading-audio-supplement.js?v=3"></script>\n'
    new = old + '    <script src="./assets/matrix-blank-input-overrides.js?v=2"></script>\n'
    changed = 0
    for path in sorted(root.glob("*.html")):
        html = path.read_text(encoding="utf-8")
        if "matrix-blank-input-overrides.js" in html or old not in html:
            continue
        path.write_text(html.replace(old, new, 1), encoding="utf-8", newline="")
        changed += 1
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pages", nargs="*", default=DEFAULT_PAGES)
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    override_path = root / "assets" / "matrix-blank-input-overrides.js"
    all_overrides = load_existing_overrides(override_path)
    total_inputs = 0
    for relative in args.pages:
        count, overrides = transform_page(root / relative)
        total_inputs += count
        all_overrides.update(overrides)
        print(f"{relative}: {count} inputs")

    add_easy_read_overrides(root, all_overrides)
    write_overrides(override_path, all_overrides)

    linked_pages = add_override_script(root)
    print(f"total: {total_inputs} inputs; linked script in {linked_pages} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
